### PR TITLE
Adding ppc64le architecture support on travis-ci

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Hi,
I had added ppc64le(Linux on Power) architecture support on travis-ci in the PR and looks like its been successfully added. I believe it is ready for the final review and merge. The travis ci build logs can be verified from the link below.
https://www.travis-ci.com/github/kishorkunal-raj/base62.js/builds/209329352

Reason behind running tests on ppc64le: This package is included in the ppc64le versions of RHEL and Ubuntu - this allows the top of tree to be tested continuously as it is for Intel, making it easier to catch any possible regressions on ppc64le before the distros begin their clones and builds. This reduces the work in integrating this package into future versions of RHEL/Ubuntu.

Please have a look.

Regards,
Kishor Kunal Raj

### CODE REVIEW

**Comment by FND** [comment]
Thanks for this, @kishorkunal-raj! I took the opportunity to migrate to GitHub Actions in #82 - but that seems to fail for non-obvious reasons. I'll take a closer look again soon (hopefully), but would welcome any assistance.

(Sorry for pinging you via multiple force-pushes there; debugging SaaS YAML can be tricky... )

**Comment by kishorkunal-raj** [comment]
Thanks for reviewing the PR and I am happy to know that you opted to migrate to github actions. As currently the ppc64le architecture is not yet supported on github actions, so it may be one of the reasons its failing. Also for information we do have plan to support ppc64le on github actions in our pipeline and team is working on it, so soon the architecture will be available there. Thanks again

**Comment by kishorkunal-raj** [comment]
Also to bring into notice that Travis is not yet dead. Travis.org is now moved to travis.com and is pretty much widely being used across the open source communities

**Comment by FND** [comment]
Oh, well, if GitHub Actions doesn't yet support ppc64le, that explains the failures... (Though I would never have guessed that based on the error output.)

In that case, I'll go ahead and merge this now (and opt not to comment further on the complex politics of Travis CI) while we wait for ppc64le support on GitHub Actions. I'd appreciate if you could ping me once that happens so we can merge #82 then.

**Comment by kishorkunal-raj** [comment]
> Oh, well, if GitHub Actions doesn't yet support ppc64le, that explains the failures... (Though I would never have guessed that based on the error output.)
> 
> In that case, I'll go ahead and merge this now (and opt not to comment further on the complex politics of Travis CI) while we wait for ppc64le support on GitHub Actions. I'd appreciate if you could ping me once that happens so we can merge #82 then.

Once the ppc architecture is enabled on github actions, I will definitely let you. Thanks for merging the PR.

**Pull request merged**
